name: Validate with hassfest

on:
  push:
  pull_request:
  #schedule:
  #  - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
        with:
          path: snoo
      - uses: home-assistant/actions/hassfest@master
