name: Validate integration

on:
  push:
  pull_request:
  #schedule:
  #  - cron: "0 0 * * *"

jobs:
  validate:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
        with:
          path: fpa
      - uses: home-assistant/actions/hassfest@master
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
