name: Validate integration

on:
  push:

jobs:
  hassfest:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
        with:
          path: fpa
      - uses: home-assistant/actions/hassfest@master
  hacs:
    runs-on: "ubuntu-latest"
    steps:
      - uses: "actions/checkout@v2"
      - name: HACS validation
        uses: "hacs/action@main"
        with:
          category: "integration"
